#!/bin/sh

set -e

export LC_CTYPE=en_US.UTF-8

set -o pipefail && xcodebuild \
-workspace Example/SSApplicationExample.xcworkspace \
-scheme SSApplicationExample \
-sdk iphonesimulator \
clean build \
ONLY_ACTIVE_ARCH=NO \
RUN_CLANG_STATIC_ANALYZER=YES \
CLANG_STATIC_ANALYZER_MODE=deep | xcpretty -c
